# Step 1: Install Chromium
- name: Install Chromium
  run: |
    sudo apt-get update
    sudo apt-get install -y chromium-browser

# Step 2: Install puppeteer-core
- name: Install dependencies
  run: npm install puppeteer-core

# Step 3: Run Puppeteer with the installed Chromium
- name: Generate PDF
  run: |
    echo "Generating PDF..."
    cat <<EOF > report.html
    <html>
    <head><title>Pull Request Report</title></head>
    <body>
      <h1>Pull Request Report</h1>
      <p>PR URL: <a href="${{ github.event.pull_request.html_url }}">${{ github.event.pull_request.html_url }}</a></p>
      <h2>Files Changed:</h2>
      <pre>
        $(git diff --name-only)
      </pre>
    </body>
    </html>
    EOF

    node -e "
    const puppeteer = require('puppeteer-core');
    (async () => {
      const browser = await puppeteer.launch({
        executablePath: '/usr/bin/chromium-browser',
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      });
      const page = await browser.newPage();
      await page.goto('file://' + process.cwd() + '/report.html');
      await page.pdf({ path: 'report.pdf', format: 'A4' });
      await browser.close();
    })();
    "
